version: '2.2'

# docker-compose up --scale redis-slave=2 --scale sentinel=3 -d

services:
  # ping redis-ha-compose_redis-master_1
  redis-master:
    image: redis:5-alpine
    command: redis-server --appendonly no

  # ping redis-ha-compose_sentinel_1
  # ping redis-ha-compose_sentinel_2
  # ping redis-ha-compose_sentinel_N
  sentinel:
    image: redis:5-alpine
    entrypoint: |
      sh -c 'sh -s <<EOF
      "/bin/sh" -c "cat <<EOF > /sentinel.conf
      port 3000
      dir /tmp
      sentinel monitor master-node redis-master 6379 2
      sentinel down-after-milliseconds master-node 5000
      sentinel parallel-syncs master-node 1
      sentinel failover-timeout master-node 5000
      EOF"
      "/bin/sh" -c "redis-sentinel /sentinel.conf"
      EOF'
    depends_on:
      - redis-master

  # ping redis-ha-compose_redis-slave_1
  # ping redis-ha-compose_redis-slave_2
  # ping redis-ha-compose_redis-slave_N
  redis-slave:
    image: redis:5-alpine
    command: redis-server --appendonly yes --aof-use-rdb-preamble yes --slaveof redis-master 6379
    depends_on:
      - redis-master

  app:
    extends:
      file: ${REDIS_HA_COMPOSE_APP_EXTENDS_FILE}
      service: ${REDIS_HA_COMPOSE_APP_EXTENDS_SERVICE}
